// Generated by LiveScript 1.6.0
(function(){
  var wn, spawn, debug;
  wn = require('when');
  spawn = require('child_process').spawn;
  debug = require('debug');
  module.exports = function(dataToSign, pemKeyAddress){
    return wn.promise(function(resolve, reject){
      var args, proc, result, errorData;
      debug('Payment[sign] keyFileAddress is: ', pemKeyAddress);
      args = ["smime", "-sign", "-inkey", pemKeyAddress, "-signer", pemKeyAddress, "-certfile", pemKeyAddress, "-noattr", "-nodetach"];
      proc = spawn('openssl', args, {
        stdio: ['pipe', 'pipe', 'pipe']
      });
      result = "";
      proc.stdout.on('data', function(data){
        return result = result + data.toString('utf8');
      });
      proc.stdout.on('end', function(end){
        return resolve(result.split("\n\n")[1]);
      });
      errorData = "";
      proc.stderr.on('data', function(data){
        return errorData = errorData + data.toString('utf8');
      });
      proc.stderr.on('end', function(data){
        if (errorData !== "") {
          error('Payment[sign]: proccess stderr end:', errorData);
          return reject(errorData);
        }
      });
      proc.on('error', function(err){
        error('Payment[sign]: proccess error:', err);
        return reject(err);
      });
      proc.on('uncaughtException', function(uncaughtException){
        error('Payment[sign]: proccess uncaughtException: ', uncaughtException);
        return reject(uncaughtException);
      });
      return proc.stdin.end(dataToSign);
    });
  };
}).call(this);
